/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    kotlin("jvm").version(libs.versions.kotlin)
    kotlin("plugin.lombok").version(libs.versions.kotlin)
    kotlin("plugin.serialization").version(libs.versions.kotlin)

    application
    alias(libs.plugins.lombok)
}

kotlin {
    jvmToolchain(25)
}

repositories {
    mavenLocal()
    mavenCentral()
}

application {
    applicationDefaultJvmArgs = listOf(
        "--enable-native-access=ALL-UNNAMED",
        "-Dstdout.encoding=UTF-8",
        "-Dstderr.encoding=UTF-8"
    )
    mainClass = "x.withlithum.neoware.main.Main"
}

lombok {
    version = "1.18.42"
}

dependencies {
    // Annotations & source
    implementation(libs.jspecify)

    // Support libraries
    implementation(libs.fastutil)
    implementation(libs.typesafe.config)
    implementation(libs.pcg)
    implementation(libs.guava)
    implementation(libs.jtoml)
    api(libs.adventure.minimessage)
    api(libs.okio)
    implementation(libs.hoplite)
    implementation(libs.hoplite.toml)
    api(libs.kotlinx.serialization)
    runtimeOnly(libs.lmax.disruptor)

    // JLine
    implementation(libs.jline)
    runtimeOnly(libs.jline.terminal.ffm)

    // Logging
    // Log4J
    implementation(libs.log4j.api)
    implementation(libs.terminalconsoleappender) {
        constraints {
            implementation(libs.log4j.core) {
                because("previous version is a Log4Shell vulnerable version")
            }
        }
    }
    runtimeOnly(libs.bundles.log4j.runtime)

    // SLF4J
    api(libs.slf4j.api)

    // Kotlin logging
    implementation(libs.kotlinlogging)

    // Core
    // Minestom
    api(libs.minestom)

    // Test libraries
    testRuntimeOnly(libs.junit.platform.launcher)
    testImplementation(libs.okio.fakefilesystem)
    testImplementation(libs.junit.jupiter)
    testImplementation(kotlin("test"))
}

tasks.test {
    useJUnitPlatform()
    testLogging {
        events("skipped", "failed")
    }
}

group = "x.withlithum.neoware"
version = "2026.1.0-alpha.1"
description = "NeoWare"
java.sourceCompatibility = JavaVersion.VERSION_25

tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc> {
    options.encoding = "UTF-8"
}
