/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    application
    `maven-publish`
    alias(libs.plugins.lombok)
}

repositories {
    mavenLocal()
    mavenCentral()
}

application {
    applicationDefaultJvmArgs = listOf(
        "--enable-native-access=ALL-UNNAMED"
    )
    mainClass = "x.withlithum.neoware.main.Main"
}

lombok {
    version = "1.18.42"
}

dependencies {
    // Annotations & source
    implementation(libs.jspecify)

    // Support libraries
    implementation(libs.fastutil)
    implementation(libs.typesafe.config)
    implementation(libs.pcg)
    implementation(libs.guava)
    implementation(libs.jtoml)
    implementation(libs.adventure.minimessage)
    runtimeOnly(libs.lmax.disruptor)

    // JLine
    implementation(libs.jline)
    runtimeOnly(libs.jline.terminal.ffm)

    // Logging
    // Log4J
    implementation(libs.log4j.api)
    implementation(libs.terminalconsoleappender) {
        constraints {
            implementation(libs.log4j.core) {
                because("previous version is a Log4Shell vulnerable version")
            }
        }
    }
    runtimeOnly(libs.bundles.log4j.runtime)

    // SLF4J
    implementation(libs.slf4j.api)

    // Core
    // Minestom
    implementation(libs.minestom)

    // Minestom PvP
    implementation(libs.minestom.pvp)

    // Test libraries
    testRuntimeOnly(libs.junit.platform.launcher)
    testImplementation(libs.junit.jupiter)
}

tasks.test {
    useJUnitPlatform()
    testLogging {
        events("passed", "skipped", "failed")
    }
}

group = "x.withlithum.neoware"
version = "2026.1.0-alpha.1"
description = "NeoWare"
java.sourceCompatibility = JavaVersion.VERSION_25

tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc> {
    options.encoding = "UTF-8"
}
