[neoware.arguments]
no_player = "Player not found"

[neoware.commands]
unknown = "Unknown command: {0}"
no_permission = "You do not have permission to execute this command"

[neoware.commands.about]
copyright = "Running Neoware - (C) WithLithum & contributors 2025-2026"
minestom = "Powered by Minestom for Minecraft: Java Edition version {0}"
source_link = "Sources"

[neoware.commands.kick]
success = "Kicked {0}"
disconnect_with_reason = "Kicked, reason: {0}"

[neoware.commands.op]
success = "Made {0} an operator"

[neoware.commands.stop]
stopping = "Stopping server"