#region Arguments
[neoware.arguments]
error = "Argument '{0}': {1}"

[neoware.arguments.entity]
too_many = "Only single entity is accepted but selector allows multiple"

[neoware.arguments.player]
name = "Invalid name or UUID"
entities = "Only players are accepted here"
not_found = "Player not found"

[neoware.commands]
unknown = "Unknown command: {0}"
no_permission = "You do not have permission to execute this command"
#endregion

#region Commands
[neoware.commands.about]
copyright = "Running Neoware - (C) WithLithum & contributors 2025-2026"
minestom = "Powered by Minestom for Minecraft Java {0}"
source_link = "Sources"

[neoware.commands.ban]
already_banned = "{0} is already banned"
success = "Banned {0}"

[neoware.commands.kick]
success = "Kicked {0}"
disconnect = "Kicked by an operator, reason: {0}"

[neoware.commands.op]
success = "Made {0} an operator"

[neoware.commands.pardon]
not_banned = "That UUID wasn't banned"
success = "Pardoned player with that UUID"

[neoware.commands.stop]
stopping = "Stopping server"
#endregion

[neoware.login.banned]
line_1 = "You have been banned from this server!"
line_2 = "Reason: \"{0}\""
line_2_no_reason = "No explanation was given for this ban."
line_3 = "This ban was given to you at {0} UTC."
line_3_no_expiry = "This ban was given to you at {0} UTC. It will not expire."
line_4 = "It will expire at {0} UTC."
line_5 = "Please contact administrator if you have any doubts or questions as to this decision."